---
- hosts: localhost
  connection: local
  vars:
    ace_box_user: "{{ lookup('env','USER') }}"
    # ace_inventory_src: https://raw.githubusercontent.com/tobigremmer-dt/on-the-fly-installer-test/main
    ace_inventory:
      - src: "{{ ace_inventory_src }}/ansible/enable.yml"
        dest: "/home/{{ ace_box_user }}/.ace/ansible/enable.yml"
      - src: "{{ ace_inventory_src }}/ansible/source-use-case.yml"
        dest: "/home/{{ ace_box_user }}/.ace/ansible/source-use-case.yml"
      - src: "{{ ace_inventory_src }}/ansible/filter_plugins/ace.py"
        dest: "/home/{{ ace_box_user }}/.ace/ansible/filter_plugins/ace.py"
  tasks:
    - name: Ensure shell recognizes Python3 libraries
      become: true
      become_user: "root"
      lineinfile:
        path: "/home/{{ ace_box_user }}/.bashrc"
        line: export PATH=/home/{{ ace_box_user }}/.local/bin:$PATH
    - name: Install apt packages
      become: true
      become_user: "root"
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - snapd
          - python3-jmespath
          - vim
          - git
          - rsync
    - name: Download ACE inventory
      file:
        path: "{{ item.dest | dirname }}"
        state: directory
        mode: "0755"
      loop: "{{ ace_inventory }}"
    - get_url:
        url: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0755"
      loop: "{{ ace_inventory }}"
